import { render } from '@testing-library/react'
import { vi } from 'vitest'
import { AppContext } from '@/app/AppContext'
import type { Screen, Route } from '@/app/AppContext'

export function makeAppContext(overrides: Partial<Parameters<typeof AppContext.Provider>[0]['value']> = {}) {
  return {
    screen: 'welcome' as Screen,
    route: { name: 'welcome' } as Route,
    goTo: vi.fn(),
    goToPath: vi.fn(),
    replace: vi.fn(),
    back: vi.fn(),
    canGoBack: false,
    originScreen: null as Screen | null,
    loading: false,
    currentUser: null,
    todayTasks: [],
    todaySubTasksMap: {},
    inboxTasks: [],
    inboxSubTasksMap: {},
    todayEnergy: null,
    todayEnergyStatus: null,
    todayPlannedTasks: [],
    settings: null,
    overloadMode: false,
    updateSettings: vi.fn().mockResolvedValue(undefined),
    exportData: vi.fn().mockResolvedValue(undefined),
    importData: vi.fn().mockResolvedValue({ ok: true }),
    deleteAllData: vi.fn().mockResolvedValue(undefined),
    selectedTaskId: null,
    selectTask: vi.fn(),
    createUser: vi.fn().mockResolvedValue(undefined),
    completeOnboarding: vi.fn().mockResolvedValue(undefined),
    saveTodayEnergy: vi.fn().mockResolvedValue(undefined),
    skipTodayEnergy: vi.fn().mockResolvedValue(undefined),
    addTask: vi.fn().mockResolvedValue(undefined),
    createTaskInbox: vi.fn().mockResolvedValue(undefined),
    moveTodoTaskToList: vi.fn().mockResolvedValue(undefined),
    scheduleTask: vi.fn().mockResolvedValue(undefined),
    getPlannedTasksForDate: vi.fn().mockResolvedValue([]),
    planTaskToday: vi.fn().mockResolvedValue(undefined),
    createDetailedTask: vi.fn().mockResolvedValue('task-1'),
    getTaskById: vi.fn().mockResolvedValue(undefined),
    duplicateTaskById: vi.fn().mockResolvedValue('task-copy-1'),
    updateTaskFields: vi.fn().mockResolvedValue(undefined),
    deleteTaskScoped: vi.fn().mockResolvedValue(undefined),
    completeTaskById: vi.fn().mockResolvedValue(undefined),
    reportTaskById: vi.fn().mockResolvedValue(undefined),
    moveTask: vi.fn().mockResolvedValue(undefined),
    completeTask: vi.fn().mockResolvedValue(undefined),
    deleteTask: vi.fn().mockResolvedValue(undefined),
    addSubTask: vi.fn().mockResolvedValue(undefined),
    deleteSubTask: vi.fn().mockResolvedValue(undefined),
    toggleSubTask: vi.fn().mockResolvedValue(undefined),
    reorderSubTasks: vi.fn().mockResolvedValue(undefined),
    getSubTasks: vi.fn().mockResolvedValue([]),
    getPlannedSubTasksForDate: vi.fn().mockResolvedValue([]),
    scheduleSubTask: vi.fn().mockResolvedValue(undefined),
    reportSubTask: vi.fn().mockResolvedValue(undefined),
    renameSubTask: vi.fn().mockResolvedValue(undefined),
    updateTaskTitle: vi.fn().mockResolvedValue(undefined),
    reorderTodayTasks: vi.fn().mockResolvedValue(undefined),
    refreshDashboard: vi.fn().mockResolvedValue(undefined),
    lists: [],
    selectedListId: null,
    selectList: vi.fn(),
    createList: vi.fn().mockResolvedValue('list-1'),
    renameList: vi.fn().mockResolvedValue(undefined),
    deleteList: vi.fn().mockResolvedValue(undefined),
    getListItems: vi.fn().mockResolvedValue([]),
    getListCategories: vi.fn().mockResolvedValue([]),
    createListCategory: vi.fn().mockResolvedValue('category-1'),
    renameListCategory: vi.fn().mockResolvedValue(undefined),
    deleteListCategory: vi.fn().mockResolvedValue(undefined),
    addListItem: vi.fn().mockResolvedValue(undefined),
    deleteListItem: vi.fn().mockResolvedValue(undefined),
    toggleListItem: vi.fn().mockResolvedValue(undefined),
    folders: [],
    tools: [],
    createFolder: vi.fn().mockResolvedValue('folder-1'),
    createToolList: vi.fn().mockResolvedValue('list-1'),
    deleteTool: vi.fn().mockResolvedValue(undefined),
    deleteFolder: vi.fn().mockResolvedValue(undefined),
    budgetCategories: [],
    budgetAccounts: [],
    budgetEntries: [],
    budgetDeposits: [],
    manualTestResults: [],
    submitManualTestResult: vi.fn().mockResolvedValue(undefined),
    createBudgetCategory: vi.fn().mockResolvedValue(undefined),
    renameBudgetCategory: vi.fn().mockResolvedValue(undefined),
    updateBudgetCategoryAmount: vi.fn().mockResolvedValue(undefined),
    deleteBudgetCategory: vi.fn().mockResolvedValue('deleted'),
    createBudgetAccount: vi.fn().mockResolvedValue(undefined),
    renameBudgetAccount: vi.fn().mockResolvedValue(undefined),
    deleteBudgetAccount: vi.fn().mockResolvedValue('deleted'),
    createBudgetEntry: vi.fn().mockResolvedValue(undefined),
    deleteBudgetEntry: vi.fn().mockResolvedValue(undefined),
    createBudgetDeposit: vi.fn().mockResolvedValue(undefined),
    deleteBudgetDeposit: vi.fn().mockResolvedValue(undefined),
    ...overrides,
  }
}

export function renderWithApp(ui: React.ReactNode, ctx = makeAppContext()) {
  return render(<AppContext.Provider value={ctx}>{ui}</AppContext.Provider>)
}
