import { render } from '@testing-library/react'
import { vi } from 'vitest'
import { AppContext } from '@/app/AppContext'
import type { Screen } from '@/app/AppContext'

export function makeAppContext(overrides: Partial<Parameters<typeof AppContext.Provider>[0]['value']> = {}) {
  return {
    screen: 'welcome' as Screen,
    goTo: vi.fn(),
    loading: false,
    currentUser: null,
    todayTasks: [],
    todaySubTasksMap: {},
    inboxTasks: [],
    inboxSubTasksMap: {},
    todayEnergy: null,
    todayEnergyStatus: null,
    todayPlannedTasks: [],
    settings: null,
    overloadMode: false,
    updateSettings: vi.fn().mockResolvedValue(undefined),
    exportData: vi.fn().mockResolvedValue(undefined),
    deleteAllData: vi.fn().mockResolvedValue(undefined),
    selectedTaskId: null,
    selectTask: vi.fn(),
    taskDetailOrigin: null,
    setTaskDetailOrigin: vi.fn(),
    taskCreateOrigin: null,
    setTaskCreateOrigin: vi.fn(),
    createUser: vi.fn().mockResolvedValue(undefined),
    completeOnboarding: vi.fn().mockResolvedValue(undefined),
    saveTodayEnergy: vi.fn().mockResolvedValue(undefined),
    skipTodayEnergy: vi.fn().mockResolvedValue(undefined),
    addTask: vi.fn().mockResolvedValue(undefined),
    createTaskInbox: vi.fn().mockResolvedValue(undefined),
    moveTodoTaskToList: vi.fn().mockResolvedValue(undefined),
    createTaskV2Dest: vi.fn().mockResolvedValue(undefined),
    scheduleV2Task: vi.fn().mockResolvedValue(undefined),
    getPlannedTasksForDate: vi.fn().mockResolvedValue([]),
    pendingPlanTask: null,
    startPlanTask: vi.fn(),
    startPlanSubTask: vi.fn(),
    clearPendingPlanTask: vi.fn(),
    schedulePendingTask: vi.fn().mockResolvedValue('taskv2-1'),
    completeV2Task: vi.fn().mockResolvedValue(undefined),
    renameV2Task: vi.fn().mockResolvedValue(undefined),
    deleteV2Task: vi.fn().mockResolvedValue(undefined),
    reportV2Task: vi.fn().mockResolvedValue(undefined),
    movingTask: null,
    startMoveTask: vi.fn(),
    startMoveSubTask: vi.fn(),
    clearMoveTask: vi.fn(),
    planningTargetDate: null,
    setPlanningTargetDate: vi.fn(),
    moveTask: vi.fn().mockResolvedValue(undefined),
    completeTask: vi.fn().mockResolvedValue(undefined),
    deleteTask: vi.fn().mockResolvedValue(undefined),
    addSubTask: vi.fn().mockResolvedValue(undefined),
    deleteSubTask: vi.fn().mockResolvedValue(undefined),
    toggleSubTask: vi.fn().mockResolvedValue(undefined),
    reorderSubTasks: vi.fn().mockResolvedValue(undefined),
    getSubTasks: vi.fn().mockResolvedValue([]),
    getPlannedSubTasksForDate: vi.fn().mockResolvedValue([]),
    scheduleSubTaskV2: vi.fn().mockResolvedValue(undefined),
    reportSubTaskV2: vi.fn().mockResolvedValue(undefined),
    renameSubTaskV2: vi.fn().mockResolvedValue(undefined),
    updateTaskTitle: vi.fn().mockResolvedValue(undefined),
    reorderTodayTasks: vi.fn().mockResolvedValue(undefined),
    refreshDashboard: vi.fn().mockResolvedValue(undefined),
    lists: [],
    selectedListId: null,
    selectList: vi.fn(),
    createList: vi.fn().mockResolvedValue('list-1'),
    renameList: vi.fn().mockResolvedValue(undefined),
    deleteList: vi.fn().mockResolvedValue(undefined),
    togglePinList: vi.fn().mockResolvedValue(undefined),
    listDetailOrigin: null,
    setListDetailOrigin: vi.fn(),
    getListItems: vi.fn().mockResolvedValue([]),
    addListItem: vi.fn().mockResolvedValue(undefined),
    deleteListItem: vi.fn().mockResolvedValue(undefined),
    ...overrides,
  }
}

export function renderWithApp(ui: React.ReactNode, ctx = makeAppContext()) {
  return render(<AppContext.Provider value={ctx}>{ui}</AppContext.Provider>)
}
